import sys
from pathlib import Path

QUESTION = """
Give a general description and parameters description. Don't be verbose.
Be to the point of the following code snippet. Format it in markdown as such:
**General Description**: ....
**Parameters Description**:

    - ....

    - ....
"""

QUESTION_CONFIG_BEFORE = """
Explain what kind of building is described in the following configuration.
Be succinct and to the point and stay with the fact:
"""

sys.path.append(str(Path(__file__).parents[2]))
from docs_src.utils import Configuration, Source, Tutorial  # noqa: E402

TUTORIALS = [
    Tutorial(
        title="Shoe-box building",
        name="hello_world",
        configuration=Configuration(
            path=Path(__file__).parents[2].joinpath("tests/tutorials/hello_world.yaml"),
            question_before=QUESTION_CONFIG_BEFORE,
            object_after="",
            question_after="Fix spelling, improve flow. Just give the answer without quotes:"
            "'The yaml configuration above will be used in the remainder "
            "of this tutorial as our output...'",
        ),
        code_blocks_source=[
            Source(
                source="test_simulate_model_buildings",
                title="Simulation using Buildings Library",
                report_path=Configuration(
                    object_after="",
                    object_before="",
                    question_before="Check spelling and improve flow. Just give the answer: "
                    "'Thie following report is automatically generated by "
                    "Trano and contains a detailed description of the "
                    "different parameters as weel as layers..'",
                    question_after="Check spelling and improve flow and add more information "
                    "given the previous ceontexts. Just give the answer: 'Apart "
                    "from metadata that are used in the models. graphs are also "
                    "generated sucn as...'",
                ),
                question=QUESTION,
            ),
            Source(
                source="test_simulate_model_ideas",
                title="Simulation using IDEAS Library",
                question=QUESTION,
            ),
        ],
    ),
    Tutorial(
        title="Multizone free float",
        name="multizone_free_float",
        configuration=Configuration(
            question_before=QUESTION_CONFIG_BEFORE,
            object_after="",
            question_after="""Fix spelling, improve flow. Just give the answer without quotes:
            'The yaml configuration above will be used in the remainder of this tutorial as our output...'""",
        ),
        code_blocks_source=[
            Source(
                source="test_multizone_free_float",
                title="Simulation using Buildings Library",
                report_path=Configuration(
                    object_after="",
                    object_before="",
                    question_before="""Check spelling and improve flow. Just give the answer: 'Thie following report is
                    automatically generated by Trano and contains a detailed description of the different parameters
                    as weel as layers..'""",
                    question_after="""Check spelling and improve flow and add more information given the previous
                    ceontexts. Just give the answer: 'Apart from metadata that are used in the models. graphs
                    are also generated sucn as...'""",
                ),
                question=QUESTION,
            )
        ],
    ),
]


def gen_docs() -> None:
    for tutorial in TUTORIALS:
        tutorial.write()


if __name__ == "__main__":
    gen_docs()
