site_name: Trano
site_description: Automated building energy simulation tool with Modelica
repo_name: trano
repo_url: https://github.com/andoludo/trano
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/trano.webp
  favicon: img/trano.webp
  language: en
plugins:
  - search
nav:
  - Trano: index.md
  - Getting-started:
    - Installation: getting-started/installation.md
  - Tutorials:
    - First simulation: tutorials/first_simulation.md
    - First model: tutorials/first_model.md
    - Two zones: tutorials/two_zones.md
    - Three zones with ideal heating: tutorials/three_zones_ideal_heating.md
    - Three zones hydronic heating: tutorials/three_zones_hydronic_heating.md
  - How-to Guides: how-to guides/index.md
  - Explanation: explanation/index.md
  - Reference:
      - Components: reference/components.md
      - Parameters: reference/parameters.md

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - markdown_include.include:
        base_path: docs
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
