[tool.poetry]
name = "neosim"
version = "0.1.0"
description = ""
authors = ["aan <andoludovic.andriamamonjy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ifcopenshell = "^0.7.0.231018"
anytree = "^2.12.1"
lxml = "^4.9.3"
pydantic = "^2.5.1"
networkx = "^3.2.1"
matplotlib = "^3.8.2"
uuid = "^1.30"
docker = "^6.1.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
