name: docs

on:
  push:
    branches:
      - mkdocs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3
          cd /usr/local/bin
          ln -s /opt/poetry/bin/poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --group docs

      - name: Build documentation
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./site
